### ISSUE TITLE
Improve the definition of core_initialize_block in the appendix

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#104]
- It needs to specifies which block's header is needed (parent or itself, it is probably itself).
   - It needs to specifies that it is called during production as well, because the appendix only it says it is called during block execution but it doesn't mention that it is called during block building as Algorithm 5.7 shows.
   - Verify that it actually being called on full client during received block execution.
   - Algorithm 5.7 building block should mention the complete name of the RT entries.

**Comment by lamafab** [comment]
Current progress:

- [x] It needs to specifies which block's header is needed (parent or itself, it is probably itself).
- [x] It needs to specifies that it is called during production as well, because the appendix only it says it is called during block execution but it doesn't mention that it is called during block building as Algorithm 5.7 shows.
- [x] Verify that it actually being called on full client during received block execution.
- [x] Algorithm 5.7 building block should mention the complete name of the RT entries.
