### ISSUE TITLE
Make install should call cargo install for rust

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#2]
The scripts for [CMake rust support](https://github.com/w3f/polkadot-re-tests/blob/master/cmake/CMakeCargo.cmake) runs "cargo build" fine  (when you write make it runs cargo build) but it doesn't support cargo install, when you issue "make install". So I had to write these unreliable lines:

https://github.com/w3f/polkadot-re-tests/blob/0137463f3224a8150b29184e56eb00308987f922/test/testers/rust-tester/CMakeLists.txt#L6

as temprory measure because I wanted all executables to go somewhere deterministic independent of the os, build, etc so I can run them by the Julia script. But the correct way of doing it is to modify the CMakeRust scripts so make install runs cargo install properly.

The original CMakeRust script is coming from this repo:

https://github.com/wayk/CMakeRust
:END:
nil:END:

**Comment by drskalman** [comment]
But what they did here:

https://github.com/w3f/polkadot-re-tests/blob/0137463f3224a8150b29184e56eb00308987f922/cmake/CMakeCargo.cmake#L60

Make it that `make build` result in `cargo build` gets called, so probably similarly we should be able to make `make install` calls `cargo install`

**Comment by fgimenez** [comment]
Pls correct me if i'm wrong but i think that the build and install cases are not the same; there's no single build target, we can't call `make build`, instead the scripts add different file targets; in `cargo_build`, depending on all the vars the target file name is determined, the cargo build command for compiling it is created and a dependency between the two is established; this way, cmake understands that, for getting the target file, it needs to run that command.

On the other hand, there's a predefined `install` target and a predefined `install()` function; every time you call that function, you define an origin and a destination for a copy operation; all these actions are added to the `install` target, and are executed when you call `make install`.

AIUI we can't apply the same approach in `cargo_build` to the `install` target, if we add new targets they will be taken into account during the build phase (`make` or `make all`); we can only modify how this reserved target works through `install()` calls, describing how to copy the products of the build to their final destination.

What we could do is extracting this logic https://github.com/w3f/polkadot-re-tests/blob/0137463f3224a8150b29184e56eb00308987f922/cmake/CMakeCargo.cmake#L7-L43 to a separate function, so that we can determine `LIB_TARGET`, `LIB_BUILD_TYPE` and `LIB_FILE` dynamically, and then add calls to `install()` with the proper values, does that make sense?

**Comment by fgimenez** [comment]
i've added an initial WIP PR here https://github.com/w3f/polkadot-re-tests/pull/6 the logic that sets `LIB_TARGET`, `LIB_BUILD_TYPE` and `LIB_FILE` is extracted to `cmake/CMakeCargoCommon.cmake`, which is then used both from `cmake/CMakeCargo.cmake` and `test/testers/rust-tester/CMakeLists.txt`, the later doesn't need anymore to depend to statically set values and should work cross-platform now using make install.

With that in place I get this locally:
```
$ make install
[100%] running cargo
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
[100%] Built target scale_codec_target
[100%] Built target scale_codec_go
[100%] Built target scale_codec_go_all
Install the project...
-- Install configuration: ""
-- Installing: /home/fgimenez/workspace/w3f/polkadot-re-tests/build/test/testers/rust-tester/scale_codec
-- Installing: /usr/local/bin/scale_codec_go
CMake Error at test/testers/go-tester/cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/home/fgimenez/workspace/w3f/polkadot-re-tests/build/test/testers/go-tester/scale_codec_go"
  to "/usr/local/bin/scale_codec_go".
Call Stack (most recent call first):
  test/testers/cmake_install.cmake:43 (include)
  cmake_install.cmake:42 (include)


Makefile:73: recipe for target 'install' failed
make: *** [install] Error 1
```
so, `rust-tester/scale_codec` is correctly installed, and we get an error from the go tester, which tries to be installed in `/usr/local/bin` because of this `install()` call https://github.com/w3f/polkadot-re-tests/blob/master/cmake/GolangSimple.cmake#L23, we could adjust this, and also maybe package all the function calls required for rust in a common function similar to go, let me know WDYT
