### ISSUE TITLE
host-spec: incooperate Alfonso's feedback

### ISSUE THREAD

**Issue by AlfonsoCev** [w3f/polkadot-spec#474]
https://w3f.github.io/polkadot-spec/develop/

This is something I should have done some time ago. I'll give some comments about the structure of this document to Florian.

**Comment by FlorianFranzen** [comment]
Result can be found here: https://hackmd.io/A7QVdOgWR_-BGdS2lW1s8g

**Comment by lamafab** [comment]
Changes based on [Alfonsos feedback](https://hackmd.io/A7QVdOgWR_-BGdS2lW1s8g), on branch `alfonso-feedback` (PR #507).

***

## Preliminaries

> There’s something weird with the way the appendices appear on the table of contents (ToC). I think there are 3 appendices (additional info, host api, runtime api), but sometimes they are numbered A to C, sometimes D to F. For instance when I’m in Host Specification, section 1 (Preliminaries), and I look at the ToC, I see only 2 sections (D: additional info, and E: Host API). Maybe it’s a good idea to create a 3rd chapter called Appendices, and put all appendices there as internal sections.

No longer relevant on `develop`.

***

> “The Polkadot Host provides the functionality for the Runtime to execute its state transition logic, such as an execution environment, I/O and consensus, shared mostly among peer-to-peer decentralized cryptographically-secured transaction systems, i.e. blockchains whose consensus system is based on the proof-of-stake.”
The sentence is too long. Are these systems the parachains? Do they have to be PoS? I thought parachains don’t need to have a consensus protocol. Some clarification is needed.

> “The Polkadot Host is planned to be stable and static for the lifetime duration of the Polkadot protocol.”
Is it actually true? It sounds unrealistic to me. I thought a good, realistic target would be something like only a handful of updates per year, which for the most part are not urgent and won’t generate forks or down time.

Clarified that part:

![image](https://user-images.githubusercontent.com/42901763/168861063-81d47db1-5f2b-4a27-8e1a-2f2764e96470.png)

***

> “The node should maintains a set of around 50 active peers at any time. New peers can be found using the discovery protocols (Section 4.4)”
Typo, should be “maintain”. Also, is the 50 peer target a lower bound or an ideal target? If lower bound, specify it and say “at least 50”.

Fixed the typo. In general, the amount of active connections the node should maintain falls under the category of "_it's implementation specific_". In case of Parity's node, it keeps that count around 50, a lower/upper bounds does not need to be specified.

***

> “Exchange neighbor packets (Section 4.8.4.5).”
All other items in the list start with “The node must” or “The node should”, so you should keep the same pattern here.

Done.

***

> The “Definitions” subsection 1.2 appears empty, while the actal definitions appear as different subsections further down. This should be fixed in some way. Also, I’m not sure but it could make sense to put in an appendix all the math, CS and coding definitions that are not unique to Polkadot and that many readers might be already familiar with. Then we can just put a link to the corresponding definition wherever a term is used. I’m thinking about graph theory terms, data structures, etc. I think in a book you put definitions first, but in a digital document it makes sense to exploit hyperlinks.

What do you mean by empty? Also, I guess we could move the common definitions (like sequence, bitwise representation, etc) into an appendix, or the "Additional Information" chapter (see [here](http://localhost:8000/polkadot-spec.html#_additional_information), which should probably be an Appendix, too. I'll discuss this in our spec sync).

***

> “A Discrete State Machine(DSM) is a state transition system whose set of states and set of transitions are countable and admits a starting state.”
There’s a space missing. Also, I’d rewrite it as: “A Discrete State Machine (DSM) is a state transition system that admits a starting state and whose set of states and set of transitions are countable”. Finally, I think it’d be nice to add some examples of a DSM, like a vending machine, an elevator, or a ledger of accounts and balances, for the reader who’s learning about it for the first time.

Updated to:

![image](https://user-images.githubusercontent.com/42901763/168872886-5cc2fc0e-2438-4ad2-afa1-0c84888ea76c.png)

Not sure about the example part, this spec is not really meant to be some sort of tutorial for beginner. But I guess it would not hurt. I'll leave this open for now.

***

> “For any vertex (B1,B2) where B1→B2 we say B2 is the parent of B1 and we indicate it by…”
I think “vertex” should be “arc” or “edge”. Also, intuitively I think the definition of a blockchain simply as a “directed path graph” is missing details. I think there must be a notion of a list of records, which are tamper proof. Throughout this document the word “blockchain” is used to mean a network of computers, a transaction system, etc., so it might be worth paying more attention to how exactly we want to define a blockchain, and then sticking to that definition.

Can you clarify why "vertex" is the wrong term here? Otherwise I agree with those points, I adjusted that definition:

![image](https://user-images.githubusercontent.com/42901763/168891037-1110a268-b01e-4c3a-8632-1329127ac857.png)

Regarding the last part, we do use the term "blockchain" quite freely to also describe the network as a whole, etc. But I don't think it's incorrect to use it that way. But it does cause conflict with the definition, technically, we might want to adjust this. I will discuss this with Syed And Florian.

***

> “Let G be the root of the block tree and B be one of its nodes. By Chain(B), we refer to the path graph from G to B in P(BT). Conversely, for a chain C=Chain(b), we define the head of C to be B, formally noted as B:=Head( C ). We define |C|, the length of C as a path graph. If B’ is another node on Chain(B), then by SubChain(B’,B) we refer to the subgraph of Chain(B) path graph which contains both B and B’ and by SubChain(B’,B) we refer to its length.”
In 2nd sentence, I think it should be the path from B to G, because if I understand correctly G is an ancestor of B, and each arc in the path goes from the child to the parent. In 3rd sentence Chain(b) should be Chain(B). In 5th sentence, there may be many paths that contain both B and B’, I guess you mean the (only) path that starts at B and ends at B’. I think the last SubChain(B’,B) should be |SubChain(B’,B)|, to refer to its length. Sometimes you write P(BT) and sometimes ( P )BT; I guess the latter is the right one.

Some points:

> In 2nd sentence, I think it should be the path from B to G, because if I understand correctly G is an ancestor of B, and each arc in the path goes from the child to the parent.

I think saying "from G to B" is correct since it refers to the history of that subchain rather than the direct path graph. You need to "travel" in that direction in order to get to the state of B (e.g. when syncing), which must be reproducible by every network participant.

>  In 3rd sentence Chain(b) should be Chain(B)
>  In 5th sentence, there may be many paths that contain both B and B’, I guess you mean the (only) path that starts at B and ends at B’. I think the last SubChain(B’,B) should be |SubChain(B’,B)|, to refer to its length.

Done, done and done.

> Sometimes you write P(BT) and sometimes ( P )BT; I guess the latter is the right one.

On the `develop` branch ([spec](https://spec.polkadot.network/)), we only use `(P)BT`.

Updated:

![image](https://user-images.githubusercontent.com/42901763/168896979-a2ca404b-5e22-4f35-aa58-890df426a2da.png)

***

> “We define the following complete order over C such that for C1,C2∈C if |C1|≠|C2| we say C1>C2 if and only if |C1|>|C2|. If |C1|=|C2| we say C1>C2 if and only if the block arrival time of Head(C1) is less than the block arrival time of Head(C2) (Section 5.2.3.7). We define the Longest-Chain(BT) too be the maximum chain given by this order.”
The first sentence is too long and a bit confusing. I’d say “We define the following complete order over C as follows. For chains C1,C2∈C, we have that C1>C2 if either |C1|>|C2|, or |C1|=|C2| and the block arrival time of Head(C1) is earlier than that of Head(C2)”. Typo in the 3rd sentence: “too” should be “to”. You should probably say that we assume that all blocks have distinct arrival times, hence why there are no ties and the relation is actually a complete order (but maybe we don’t actually need a complete order in our model? and there’s no need for this assumption?). You should also mention that since a block’s arrival time is different for each node, the total order defined is also different for each node.

Block arrival time is entirely subjective, of course. The question is when you have two forks with the same length, then what should one do? Technically this is implementation specific: the node can pick anyone. This does not need to be specced, but we can just say "take the one you got first".

Updated:

![image](https://user-images.githubusercontent.com/42901763/169040837-6cb3f67a-0a8b-4f6c-a3d7-a181d276da1d.png)

***

> “We say B is descendant of B’, formally noted as B>B’ if B is a descendant of B’ in the block tree.”
Are you guys kidding with this definition? Also, it’d make sense to also define ancestor in the same definition, if that term is ever used.

😂 We don't really reference that definition directly anywhere, but I'll leave it for context.

Updated:

![image](https://user-images.githubusercontent.com/42901763/169060506-ef91b35e-b913-45f3-893b-11e9ba29bbdd.png)

***

## State specification 

> “The Trie is used to compute the state root, Hr, (Definition 31), whose purpose is to authenticate the validity of the state database. Thus, the Polkadot Host follows a rigorous encoding algorithm to compute the values stored in the trie nodes to ensure that the computed Merkle hash, Hr, matches across the Polkadot Host implementations.”
Here I would clarify that we use the trie as a Merkle tree, which in turn is a type of cryptographic commitment scheme. These are standard terms (known at least by theoreticians), so they’d help the reader immediately understand what’s going on.

Done.

***

> “When traversing the Trie to a specific node, its key can be reconstructed by concatenating the subsequences of the key which are stored…”
Should be “the keys”.

Done.

***

> “To identify the node corresponding to a key value, k, first we need to encode k in a consistent with the Trie structure way.”
I’d say “in a way consistent with the Trie structure”. I think you guys are thinking in German :)

Done.

***

> “For each node, part of kN is built while the trie is traversed from root to N part of kN is stored in N”
Should be “from the root to N and another part of kN is stored in N”. Also, sometimes you write trie with an uppercase T and sometimes you don’t; you should pick one notation.

Done and done (using lowercase "trie" except in titles).

***

> “where pk_N^Agr is a suffix subsequence of k_N”
I think it should be a prefix.

Done

***

> “where K is defined Definition 16”
there’s an “in” missing. Further down a “teh” should be “the”. Having some figures and examples would be great to explain the trie structure.

No longer relevant on `develop`, but we could add some examples to the trie structure, maybe. I'll discuss this with the team.

***

> In definition 25 (Children bitmap), “We define where bit bi:=1 if N has a child with partial key i” sounds weird. I’d say: “We define bit bi to be 1 if and only if N has a child with partial key i”

I think dropping the "where" works too, updated:

![image](https://user-images.githubusercontent.com/42901763/169070974-41fe66e9-17b7-4ab8-935c-c7002c43ba10.png)

***

> “The Trie deviates from a traditional Merkle tree where node value (Definition 23), vN, is presented instead of its hash if it occupies less space than its hash.”
I’d say “The trie deviates from a traditional Merkle tree in that a node value…”

Done, used "the node value..." instead of "a node value...", though.

***

> In definition 28 (Merkle value), I think the condition N+R should be N=R.

Correct, done.

**Comment by FlorianFranzen** [comment]
Fixed in #507
