### ISSUE TITLE
host-spec: incooperate Handan's feedback

### ISSUE THREAD

**Issue by FlorianFranzen** [w3f/polkadot-spec#501]
See w3f/research-internal#849

**Comment by lamafab** [comment]
Fixed as part of #502 because that PR contains changes to the Consensus chapter.

Based on Handans review:

## In: Winning Threshold

![image](https://user-images.githubusercontent.com/42901763/168826422-22bf3281-4e37-4b2e-8ee3-da5dc03c1b17.png)

Done:

![image](https://user-images.githubusercontent.com/42901763/168826638-7e278223-9967-45a3-9e08-ba085b9e6c41.png)

## In: Primary Block Production Lottery

![image](https://user-images.githubusercontent.com/42901763/168827486-943b1f8a-ae6e-4b66-af24-44d77ac7fbab.png)

Done:

![image](https://user-images.githubusercontent.com/42901763/168827616-34a4d6fc-4444-484c-a94e-d47a5a728c05.png)

## In: Block Arrival Time

![image](https://user-images.githubusercontent.com/42901763/168828385-a3f15264-e1f9-4164-bee2-0335c8885560.png)

I removed that section for now. Afaik there is no check on block arrival times, meaning that a block could be sent too early or too late. Anyway, block production (alternative producers, secondary slots) and finality basically take care of that.

## In: Verify Authorship Right

![image](https://user-images.githubusercontent.com/42901763/168829455-3aa7b451-083e-419f-9557-cc4b8e0acc77.png)

Done:

![image](https://user-images.githubusercontent.com/42901763/169035347-e910f254-e21e-448c-aeb0-90e1636f083c.png)

![image](https://user-images.githubusercontent.com/42901763/168834884-5831ca12-2af0-428b-af74-f87767683ef2.png)

**Comment by lamafab** [comment]
See https://github.com/w3f/polkadot-spec/issues/501#issuecomment-1128939572
