### ISSUE TITLE
Write up the RPC standard

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#67]
This can be done following the Substrate code. It should probably be a different indepenedent document.

**Comment by lamafab** [comment]
Current version: https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md

**Comment by drskalman** [comment]
Florian is going to review it and gives feedback.

**Comment by lamafab** [comment]
(Feedback from Florian)

*Can be done (by me):*
- [x] It might improve clearity to reference and use RFC 2119 
- [x] Failure states and error codes are not referenced at all
  - [x] PSP should describe common shared failures codes
  - [x] PSP should reserve section for future assignment of errors
  - [x] PSP should reserve section for implementation specific errors
  - [x] Calls that can fail in expected ways in normal operation should state so
- [x] system_accountNextIndex could also be account_nextIndex
- [x] Group together all author call that handle extrinsics
- [x] Last table of content item links to Engine instead of Payment
- [x] Mention which function are safe and unsafe to expose.
- [x] Mention two flags; one for exposing *safe* RPC on every interface, one to exposing *unsafe* RPC for every interface.

*Clarify with Florian:*
- [ ] There is no API for intrinsics
- [x] Most JSON RPC protocols use '.' instead of '_' as separator
  - (*edit: design was influenced by the Ethereum JSON-RPC and will be kept that way.*)

*Discuss with Parity:*
- [ ] author has no API to ~~list or~~ remove keys
- [ ] Chain could be renamed Onchain
- [ ] Chain getBlockHash should always return a result or else fail
- [ ] Offchain calls should not contain the word local if the support other storage as well
- [ ] state_getPairs might be better named getKeys for concistency
- [ ] RPC should be disabled by default.

**Comment by drskalman** [comment]
Puting speccing of Contract API on hold based on peter: maybe just restrict it [RPC API] to APIs for relay chain host for now? or at least clearly separate them

**Comment by FlorianFranzen** [comment]
Here is the info about the whole ```state_getPairs``` debate before it gets lost on riot: [This](https://github.com/paritytech/substrate/pull/4718) is the pull request that deprecated ```state_getKeys``` and [here](https://github.com/paritytech/substrate/pull/4803) is the one that introduced ```state_getPairs```.

**Comment by drskalman** [comment]
- @FlorianFranzen makes an issue on substrate repo about the safety issue with the RPC.
 - @FlorianFranzen reviews and then submit the pull request for review to Bruno and then close the issue

**Comment by FlorianFranzen** [comment]
There is currently a lot of uncertainty on what to do about RPC feature flags.

**Comment by FlorianFranzen** [comment]
Looks good to me now, apart from the following section:

> The implementation of this specification should disable the JSON-RPC API by default. When enabled, the API should only accept requests from localhost. Additionally, two options should be available and have to be explicitly enabled: an option to expose *SAFE* functions on every interface, and another option to expose *UNSAFE* functions on every interface.

I think we should make sure to cover all possible cases clearly. I would therefore write something like this:

The implementation should disable the JSON-RPC API by default. It should then be possible to separately enable the *SAFE* and *UNSAFE* API through command line flags for different scopes and sockets. A implementation should at least support the local (listening on 127.0.0.1, [::1], etc) and public scope (listening to any interface) as well as net and web sockets (and optionally unix sockets). 

For example:
| API / Network | Localhost  | All interfaces |
| ------------ | ------------- | ------------- |
| Safe API     | `--local-{rpc\|ws}` | `--public-{rpc\|ws}` |
| Unsafe API | `--local-unsafe-{rpc\|ws}` | `--public-unsafe-{rpc\|ws}` |

About the second point: Currently Parity does not seem to have made up their mind which way to go either:
 - [Substrate Wiki - Public RPC](https://github.com/paritytech/substrate/wiki/Public-RPC)
 - paritytech/substrate#2303
 - paritytech/substrate#5233
 - paritytech/substrate#5385

I would therefore like to wait till we all agree on what to require before we contact them.
